nom035/nom035/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from users.views import login_view, index_view, user_logout, _404, _500

urlpatterns = [
    path('surveys/', include('surveys.urls', namespace="survey")),
    path('user/', include('users.urls', namespace="user")),
    path('management/', admin.site.urls),
    path('login/', login_view, name='login_view'),
    path('logout/', user_logout, name='user_logout'),
    path('', index_view, name='index_view'),
]

handler404 = _404
handler500 = _500

nom035/surveys/urls.py
from django.urls import path

from .views import *

app_name = "surveys"

urlpatterns = [
    path("", surveys_view, name="surveys_view"),
    path("<int:survey_id>", survey_details_view, name="survey_details_view"),
    path("report/<int:survey_id>", survey_report_view, name="survey_report_view"),
    path("assign_surveys", assign_surveys, name="assign_surveys"),
    path("create_survey", create_survey, name="create_survey"),
    path("download_surveys/<int:survey_id>", download_surveys, name="download_surveys"),
    path("retrieve/<int:survey_id>", load_survey_data, name="load_survey_data"),
    path("update/<int:survey_id>", update_survey, name="update_survey"),
    path("delete/<int:survey_id>", delete_survey, name="delete_survey"),
    path("respond_survey/<int:survey_id>", respond_survey, name="respond_survey"),
]

nom035/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('employees/retrieve/<int:employee_id>', load_employee_data, name='load_employee_data'),
    path('employees/register/', register_employee, name='register_employee'),
    path('employees/update/<int:employee_id>', update_employee, name='update_employee'),
    path('employees/delete/<int:employee_id>', delete_employee, name='delete_employee'),
    path('employees/', employees_view, name='employees_view'),
    path('employees/<int:employee_id>/<int:survey_id>', employee_answers_view, 
        name='employee_answers_view'),
    path('employees/<int:employee_id>', employee_details_view, 
        name='employee_details_view'),
    path('policy/', policy_view, name='policy_view'),
    path('update_password/', update_password, name='update_password'),
]

nom035/templates/_alerts.html
{% if messages %}
{% for message in messages %}
<div id="message" class="container">
  <div class="alert alert-{{message.tags}} alert-dismissible text-center" role="alert">
    <strong>
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      Error:
      {% else %}
      {{ message.tags|title }}
      {% endif %}
    </strong>
    {{ message }}
  </div>
</div>
{% endfor %}
{% endif %}

nom035/templates/_footer.html
<footer class="footer-copyright p-2">
  <h6>&nbsp &nbsp Copyright ©
    <script>document.write(new Date().getFullYear())</script> <strong>JIAV</strong> Todos los derechos reservados.
  </h6>
</footer>

nom035/templates/_navbar.html
{% load static %}

{% url 'index_view' as index_url %}
{% url 'survey:surveys_view' as survey_url %}
{% url 'user:employees_view' as employee_url %}
{% url 'user:policy_view' as policy_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index_view' %}">
    <img src="{% static 'img/jiav_logo.png' %}" height="30" alt="" loading="lazy">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
    <ul class="navbar-nav mr-auto">
      <li>
        <a class="nav-link {% if request.path == index_url %} active {% endif %}"
          href="{% url 'index_view'%}">Inicio</a>
      </li>
      {% if user.company %}
      <li>
        <a class="nav-link {% if request.path == survey_url %} active {% endif %}"
          href="{% url 'survey:surveys_view' %}">Encuestas</a>
      </li>
      <li>
        <a class="nav-link {% if request.path == employee_url %} active {% endif %}"
          href="{% url 'user:employees_view' %}">Empleados</a>
      </li>
      {% endif %}
      <li>
        <a class="nav-link {% if request.path == policy_url %} active {% endif %}"
          href="{% url 'user:policy_view' %}">Política</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li>
        <a class="nav-link mr-3" href="{% url 'user_logout' %}">
          Logout
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-door-open-fill" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M1.5 15a.5.5 0 0 0 0 1h13a.5.5 0 0 0 0-1H13V2.5A1.5 1.5 0 0 0 11.5 1H11V.5a.5.5 0 0 0-.57-.495l-7 1A.5.5 0 0 0 3 1.5V15H1.5zM11 2v13h1V2.5a.5.5 0 0 0-.5-.5H11zm-2.5 8c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z" />
          </svg>
        </a>
      </li>
    </ul>
  </div>
</nav>

nom035/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NOM 035</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script>
    var test = document.createElement("div")
    test.className = "hidden d-none"
    document.head.appendChild(test)
    var cssLoaded = window.getComputedStyle(test).display === "none"
    document.head.removeChild(test)

    if (!cssLoaded) {
      var link = document.createElement("link");

      link.type = "text/css";
      link.rel = "stylesheet";
      link.href = "{% static 'css/bootstrap.min.css' %}";

      document.head.appendChild(link);
    }
  </script>
</head>

<body>

  {% include '_navbar.html' %}

  {% block content %}
  {% endblock %}

  {% include '_footer.html' %}
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"
    integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg=="
    crossorigin="anonymous"></script>
  <script>window.jQuery || document.write(`<script src="{% static 'js/jquery-3.5.1.min.js' %}"><\/script>`)</script>
  <script>if (typeof ($.fn.modal) === 'undefined') { document.write(`<script src="{% static 'js/bootstrap.bundle.min.js' %}"><\/script>`) };</script>
  <script type="text/JavaScript" src="{% static 'js/main.js' %}"></script>
</body>

</html>

nom035/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
  <div class="bg-login">
    <div class="container-fluid bg-login-form full-height d-flex align-items-center justify-content-center">
      <div class="col-md-8 col-lg-8 col-xl-6">
        <div class="card dark border-0">
          <h5 class="card-header bg-dark text-white">Iniciar Sesión</h5>
          <div class="card-body">
            <!-- Alerts -->
            <div class="row">
              <div class="col-lg-8 offset-lg-2">
                {% include '_alerts.html' %}
              </div>
            </div>
            <form method="POST" action="{% url 'login_view' %}">
              {% csrf_token %}
              <div class="form-group">
                <label for="username">Usuario</label>
                <input type="text" class="form-control" id="username" name="username" aria-describedby="usernameHelp">
                <div id="validationServer03Feedback" class="invalid-feedback">
                  Please provide a valid city.
                </div>
              </div>
              <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="password" class="form-control" id=" password" name="password">
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>