nom035/nom035/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from users.views import login_view, index_view, user_logout, _404, _500

urlpatterns = [
    path('surveys/', include('surveys.urls', namespace="survey")),
    path('user/', include('users.urls', namespace="user")),
    path('management/', admin.site.urls),
    path('login/', login_view, name='login_view'),
    path('logout/', user_logout, name='user_logout'),
    path('', index_view, name='index_view'),
]

handler404 = _404
handler500 = _500

nom035/surveys/urls.py
from django.urls import path

from .views import *

app_name = "surveys"

urlpatterns = [
    path("", surveys_view, name="surveys_view"),
    path("<int:survey_id>", survey_details_view, name="survey_details_view"),
    path("report/<int:survey_id>", survey_report_view, name="survey_report_view"),
    path("assign_surveys", assign_surveys, name="assign_surveys"),
    path("create_survey", create_survey, name="create_survey"),
    path("download_surveys/<int:survey_id>", download_surveys, name="download_surveys"),
    path("retrieve/<int:survey_id>", load_survey_data, name="load_survey_data"),
    path("update/<int:survey_id>", update_survey, name="update_survey"),
    path("delete/<int:survey_id>", delete_survey, name="delete_survey"),
    path("respond_survey/<int:survey_id>", respond_survey, name="respond_survey"),
]

nom035/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('employees/retrieve/<int:employee_id>', load_employee_data, name='load_employee_data'),
    path('employees/register/', register_employee, name='register_employee'),
    path('employees/update/<int:employee_id>', update_employee, name='update_employee'),
    path('employees/delete/<int:employee_id>', delete_employee, name='delete_employee'),
    path('employees/', employees_view, name='employees_view'),
    path('employees/<int:employee_id>/<int:survey_id>', employee_answers_view, 
        name='employee_answers_view'),
    path('employees/<int:employee_id>', employee_details_view, 
        name='employee_details_view'),
    path('policy/', policy_view, name='policy_view'),
    path('update_password/', update_password, name='update_password'),
]

nom035/users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Company(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    social_denomination = models.CharField(max_length=180)
    address = models.CharField(max_length=300)
    main_activity = models.CharField(max_length=200)
    employees_code = models.CharField(max_length=4)

    def __str__(self):
        return self.social_denomination


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(
        "Company", on_delete=models.CASCADE, related_name="employees"
    )
    sex = models.BooleanField(null=True)
    birthdate = models.DateField(default=timezone.now)
    policy = models.BooleanField(default=False)

    @property
    def age(self):
        import datetime

        return int((datetime.date.today() - self.birthdate).days / 365.25)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


class InformationLog(models.Model):
    employee = models.ForeignKey(
        "Employee", on_delete=models.CASCADE, related_name="information_logs"
    )
    civil_status = models.IntegerField(null=True)
    educational_level = models.IntegerField(null=True)
    position = models.CharField(max_length=100, null=True)
    area = models.CharField(max_length=70, null=True)
    position_type = models.IntegerField(null=True)
    contract_type = models.IntegerField(null=True)
    personnel_type = models.IntegerField(null=True)
    working_day_type = models.IntegerField(null=True)
    shift_rotation = models.BooleanField(null=True)
    current_position_time = models.IntegerField(null=True)
    work_experience_time = models.IntegerField(null=True)

nom035/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import *
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from surveys.models import AnswerSheet, Survey

from . import choices
from .models import Employee, InformationLog


def login_view(request):
    if request.user.is_authenticated:
        return redirect("index_view")
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("index_view")
        else:
            messages.error(request, "El usuario o la contraseña son inconrrectos.")
            return redirect("login_view")
    else:
        return render(request, "login.html")


# Posible mejora
def user_logout(request):
    logout(request)
    return redirect("login_view")


def index_view(request):
    if request.user.is_authenticated:
        employee = is_employee(request.user)
        company = is_company(request.user)
        surveys = []
        graph_data = None
        rca = None  # Require clinical attention
        if company is not None:
            company = request.user.company
            surveys = company.surveys.order_by("-id")[:2]
            if surveys:
                rca, graph_data = company_index_data(surveys)
        else:
            employee = request.user.employee
            sheets = employee.answer_sheets.filter(final_answer="unanswered").order_by(
                "-id"
            )
            for sheet in sheets:
                surveys.append(sheet.survey)
        context = {
            "employee": employee,
            "company": company,
            "surveys": surveys,
            "graph_data": graph_data,
            "require_clinical_attention": rca,
        }
        return render(request, "users/index.html", context)
    else:
        return redirect("login_view")


def register_employee(request):
    if request.method == "POST":
        username = request.POST["username"]
        pwd = request.POST["password"]
        pwd_conf = request.POST["password_confirmation"]
        f_name = request.POST["first_name"]
        l_name = request.POST["last_name"]
        email = request.POST["email"]
        sex = request.POST["sex"]
        b_date = request.POST["birthdate"]
        civ_st = request.POST["civil_status"]
        educ_lvl = request.POST["educational_level"]
        pos = request.POST["position"]
        area = request.POST["area"]
        pos_type = request.POST["position_type"]
        contr_type = request.POST["contract_type"]
        pers_type = request.POST["personnel_type"]
        work_d_type = request.POST["working_day_type"]
        shft_rot = request.POST["shift_rotation"]
        curr_pos_t = request.POST["current_position_time"]
        work_exp_t = request.POST["work_experience_time"]

        company = is_company(request.user)
        if company is not None:
            employee_code = company.employees_code
            username = employee_code + username
        else:
            return redirect(_404(request, "Page not found", "404.html"))
        if User.objects.filter(username=username).exists():
            messages.error(request, "El nombre de usuario ya existe, prueba con otro")
            return redirect("user:employees_view")
        if User.objects.filter(email=email).exists():
            messages.error(request, "El email ingresado ya existe, prueba con otro")
            return redirect("user:employees_view")
        if pwd != pwd_conf and pwd != "":
            messages.error(request, "Las contraseñas no coinciden")
            return redirect("user:employees_view")
        new_user = User.objects.create_user(
            username=username,
            email=email,
            password=pwd,
            first_name=f_name,
            last_name=l_name,
        )
        employee = Employee.objects.create(
            user=new_user, sex=sex, birthdate=b_date, company=company
        )
        InformationLog.objects.create(
            employee=employee,
            civil_status=civ_st,
            educational_level=educ_lvl,
            position=pos,
            area=area,
            position_type=pos_type,
            contract_type=contr_type,
            personnel_type=pers_type,
            working_day_type=work_d_type,
            shift_rotation=shft_rot,
            current_position_time=curr_pos_t,
            work_experience_time=work_exp_t,
        )
    return redirect("user:employees_view")


def update_employee(request, employee_id):
    if request.method == "POST":
        f_name = request.POST["first_name"]
        l_name = request.POST["last_name"]
        email = request.POST["email"]
        pwd = request.POST["password"]
        pwd_conf = request.POST["password_confirmation"]
        b_date = request.POST["birthdate"]
        civ_st = request.POST["civil_status"]
        educ_lvl = request.POST["educational_level"]
        pos = request.POST["position"]
        area = request.POST["area"]
        pos_type = request.POST["position_type"]
        contr_type = request.POST["contract_type"]
        pers_type = request.POST["personnel_type"]
        work_d_type = request.POST["working_day_type"]
        shft_rot = request.POST["shift_rotation"]
        curr_pos_t = request.POST["current_position_time"]
        work_exp_t = request.POST["work_experience_time"]

        company = is_company(request.user)
        if company is not None:
            employee = get_object_or_404(Employee, id=employee_id)
            if employee.company == company:
                info = employee.information_logs.last()
            else:
                return redirect(_404(request, "Page not found", "404.html"))
        else:
            return redirect(_404(request, "Page not found", "404.html"))
        if pwd != "":
            if pwd != pwd_conf:
                messages.error(request, "Las contraseñas no coinciden")
            else:
                valid_pwd = password_validation(pwd)
                if valid_pwd == 0:
                    employee.user.set_password(pwd)
                else:
                    messages.error(request, valid_pwd)
        if User.objects.filter(email=email).exists() and employee.user.email != email:
            messages.error(request, "El email ingresado ya existe, prueba con otro")
        else:
            employee.user.email = email
        employee.birthdate = b_date
        employee.user.first_name = f_name
        employee.user.last_name = l_name
        employee.save()
        employee.user.save()
        InformationLog.objects.get_or_create(
            employee=employee,
            civil_status=civ_st,
            educational_level=educ_lvl,
            position=pos,
            area=area,
            position_type=pos_type,
            contract_type=contr_type,
            personnel_type=pers_type,
            working_day_type=work_d_type,
            shift_rotation=shft_rot,
            current_position_time=curr_pos_t,
            work_experience_time=work_exp_t,
        )
    return redirect("user:employees_view")


def load_employee_data(request, employee_id):
    if request.user.is_authenticated:
        company = is_company(request.user)
        if company is None:
            return redirect(_404(request, "Page not found", "404.html"))
        employee = get_object_or_404(Employee, id=employee_id)
        information_log = employee.information_logs.last()
        if employee.company == company:
            employee = [
                {
                    "first_name": employee.user.first_name,
                    "last_name": employee.user.last_name,
                    "email": employee.user.email,
                    "birthdate": employee.birthdate,
                    "civil_status": information_log.civil_status,
                    "educational_level": information_log.educational_level,
                    "position": information_log.position,
                    "area": information_log.area,
                    "position_type": information_log.position_type,
                    "contract_type": information_log.contract_type,
                    "personnel_type": information_log.personnel_type,
                    "working_day_type": information_log.working_day_type,
                    "shift_rotation": information_log.shift_rotation,
                    "current_position_time": information_log.current_position_time,
                    "work_experience_time": information_log.work_experience_time,
                }
            ]
            return JsonResponse(employee, content_type="application/json", safe=False)
    return redirect("index_view")


def password_validation(password):
    validators = [
        MinimumLengthValidator,
        CommonPasswordValidator,
        NumericPasswordValidator,
    ]
    try:
        for validator in validators:
            validator().validate(password)
        return 0
    except ValidationError as e:
        if (
            str(e)
            == "['This password is too short. It must contain at least 8 characters.']"
        ):
            return "La contraseña es demasiado corta. Debe contener por lo menos 8 caracteres"
        elif str(e) == "['This password is too common.']":
            return "La contraseña es muy común."
        elif str(e) == "['This password is entirely numeric.']":
            return "La contraseña no puede ser enteramente numérica. Añade letras y símbolos."
        else:
            return str(e)


def delete_employee(request, employee_id):
    company = is_company(request.user)
    if request.user.is_authenticated and company is not None:
        employee = get_object_or_404(Employee, id=employee_id)

nom035/templates/users/company/_summary_I.html
<div class="container">
  <div class="col-12">
    <div class="card mb-4 shadow-lg">
      <div class="card-header d-flex justify-content-center">
        Gráfica de Resultados
      </div>
      <div class="row">
        <!-- Grafica -->
        <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
          <div class="card-body">
            <canvas id="guide_I_chart" height=300% data-graph-no={{graph_data.0}} data-graph-si={{graph_data.1}}>
            </canvas>
          </div>
        </div>
        <!-- Tabla -->
        <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
          <div class="card-body">
            <table class="table table-dark table-hover">
              <thead>
                <tr>
                  <th scope="col">Requiere Atención</th>
                  <th class="text-center" scope="col">Total</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td style="background-color:#E84258;">Si</td>
                  <td class="text-center">{{graph_data.1}}</td>
                </tr>
                <tr>
                  <td style="background-color:#58A1D9;">No</td>
                  <td class="text-center">{{graph_data.0}}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

nom035/templates/users/company/_summary_II_III.html
<div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
  <div class="card mb-4 shadow-lg">
    <div class="card-header d-flex justify-content-center">
      Gráfica de Resultados
    </div>
    <div class="row">
      <!-- Grafica -->
      <div class="col col-12 col-sm-12 col-md-12 col-lg-5 col-xl-5">
        <div class="card-body">
          <canvas id="guide_II_III_chart" height=400% data-graph-nulo={{graph_data.0}} data-graph-bajo={{graph_data.1}}
            data-graph-medio={{graph_data.2}} data-graph-alto={{graph_data.3}}
            data-graph-muy-alto={{graph_data.4}}></canvas>
        </div>
      </div>
      <!-- Tabla -->
      <div class="col d-none d-sm-inline col-12 col-sm-12 col-md-12 col-lg-7 col-xl-7">
        <div class="card-body">
          <table class="table table-dark">
            <thead>
              <tr class="d-flex">
                <th class="col-3 text-center align-self-center border-0">Nivel de Riesgo
                </th>
                <th class="col-7 text-center align-self-center border-0">Necesidad de Accíon
                </th>
                <th class="col-2 text-center align-self-center border-0">Total</th>
              </tr>
            </thead>
            <tbody>
              <tr class="d-flex" style="background-color:#E84258;">
                <td class="col-3 text-center align-self-center border-0">Muy Alto</td>
                <td class="col-7 bg-dark">
                  Se requiere realizar el análisis de cada categoría y dominio para
                  establecer las acciones de intervención apropiadas, mediante un Programa
                  de intervención que deberá incluir evaluaciones específicas, y
                  contemplar campañas de sensibilización, revisar la política de
                  prevención de riesgos psicosociales y programas para la prevención de
                  los factores de riesgo psicosocial, la promoción de un entorno
                  organizacional favorable y la prevención de la violencia laboral, así
                  como reforzar su aplicación y difusión.
                </td>
                <td class="col-2 text-center align-self-center border-0">{{graph_data.4}}
                </td>
              </tr>
              <tr class="d-flex" style="background-color:#FD8060;">
                <td class="col-3 text-center align-self-center border-0">Alto</td>
                <td class="col-7 bg-dark">
                  Se requiere realizar un análisis de cada categoría y dominio, de manera
                  que se puedan determinar las acciones de intervención apropiadas a
                  través de un Programa de intervención, que podrá incluir una evaluación
                  específica y deberá incluir una campaña de sensibilización, revisar la
                  política de prevención de riesgos psicosociales y programas para la
                  prevención de los factores de riesgo psicosocial, la promoción de un
                  entorno organizacional favorable y la prevención de la violencia
                  laboral, así como reforzar su aplicación y difusión.
                </td>
                <td class="col-2 text-center align-self-center border-0">{{graph_data.3}}
                </td>
              </tr>
              <tr class="d-flex" style="background-color:#FEE191;">
                <td class="col-3 text-dark text-center align-self-center border-0">Medio
                </td>
                <td class="col-7 bg-dark">
                  Se requiere revisar la política de prevención de riesgos psicosociales y
                  programas para la prevención de los factores de riesgo psicosocial, la
                  promoción de un entorno organizacional favorable y la prevención de la
                  violencia laboral, así como reforzar su aplicación y difusión, mediante
                  un Programa de intervención.
                </td>
                <td class="col-2 text-dark text-center align-self-center border-0">
                  {{graph_data.2}}</td>
              </tr>
              <tr class="d-flex" style="background-color:#B0D8A4;">
                <td class="col-3 text-center align-self-center border-0">Bajo</td>
                <td class="col-7 bg-dark">
                  Es necesario una mayor difusión de la política de prevención de riesgos
                  psicosociales y programas para: la prevención de los factores de riesgo
                  psicosocial, la promoción de un entorno organizacional favorable y la
                  prevención de la violencia laboral.
                </td>
                <td class="col-2 text-center align-self-center border-0">{{graph_data.1}}
                </td>
              </tr>
              <tr class="d-flex" style="background-color:#58A1D9;">
                <td class="col-3 text-center align-self-center border-0">Nulo</td>
                <td class="col-7 bg-dark">
                  El riesgo resulta despreciable por lo que no se requiere medidas
                  adicionales.
                </td>
                <td class="col-2 text-center align-self-center border-0">{{graph_data.0}}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

nom035/templates/users/company/company_index.html
<div class="row mt-3">
  <div class="col-12 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-6 offset-xl-3">
    {% include '_alerts.html' %}
  </div>
</div>
<div class="container-fluid">
  <div class="text-center">
    <h2>{{company.social_denomination}}</h2>
    <button type="button" class="btn btn-outline-info rounded-pill mb-3 btn-sm" data-toggle="modal"
      data-target="#updatePasswordModal">
      Cambiar Contraseña
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-key-fill" fill="currentColor"
        xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
      </svg>
    </button>
    <h5 class="card-header bg-white border-0 text-center text-monospace">Últimos resultados ({{surveys.0.date}})</h5>
  </div>
</div>
{% if surveys %}
<!-- Resumen de Resultados -->
<!-- Resultados cuando hay guia II o III -->
{% if surveys.1.guide_number > 1 %}
<div class="card-body">
  <div class="row">
    {% include './_summary_II_III.html' %}
  </div>
</div>

<!-- Resultados cuando solo hay guia I -->
{% else %}
{% include './_summary_I.html' %}
{% endif %}
<!-- Lista Guia I -->
<div class="container">
  <div class="card text-center">
    <div class="card-header bg-danger text-white">
      <h4>Requieren atención clínica:</h4>
    </div>
    <div class="card-body">
      {% for answer_sheet in require_clinical_attention %}
      <div class="row">
        <div class="col text-monospace">
          <h5>{{answer_sheet.employee.user.first_name}} {{answer_sheet.employee.user.last_name}}
            ({{answer_sheet.employee.user.username}})</h5>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% elif user.company.employees %}
<div class="card">
  <h5 class="card-header text-center">¡Bienvenido!</h5>
  <div class="card-body">
    <h5 class="card-title">Crea tu primer encuesta.</h5>
    <p class="card-text">Para iniciar una encuesta puedes acceder desde el menú <a
        href="{% url 'survey:surveys_view'%}">Encuestas</a>,
      o dando clic en el siguiente botón. No olvides registrar a tus empleados en el menú <a
        href="{% url 'user:employees_view'%}">Empleados</a>.</p>
    <a href="{% url 'survey:create_survey'%}" class="btn btn-success">Iniciar encuesta</a>
  </div>
</div>
{% else %}
<div class="card">
  <h5 class="card-header text-center">¡Bienvenido!</h5>
  <div class="card-body">
    <h5 class="card-title">Registra a tus empleados.</h5>
    <p class="card-text">Para registrara a tus empleados puedes acceder desde el menú <a
        href="{% url 'user:employees_view'%}">Empleados</a>,
      o dando clic en el siguiente botón.<a href="">Empleados</a>.</p>
    <a href="{% url 'user:employees_view'%}" class="btn btn-success">Iniciar encuesta</a>
  </div>
</div>
{% endif %}