nom035/nom035/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from users.views import login_view, index_view, user_logout, _404, _500

urlpatterns = [
    path('surveys/', include('surveys.urls', namespace="survey")),
    path('user/', include('users.urls', namespace="user")),
    path('management/', admin.site.urls),
    path('login/', login_view, name='login_view'),
    path('logout/', user_logout, name='user_logout'),
    path('', index_view, name='index_view'),
]

handler404 = _404
handler500 = _500

nom035/surveys/urls.py
from django.urls import path

from .views import *

app_name = "surveys"

urlpatterns = [
    path("", surveys_view, name="surveys_view"),
    path("<int:survey_id>", survey_details_view, name="survey_details_view"),
    path("report/<int:survey_id>", survey_report_view, name="survey_report_view"),
    path("assign_surveys", assign_surveys, name="assign_surveys"),
    path("create_survey", create_survey, name="create_survey"),
    path("download_surveys/<int:survey_id>", download_surveys, name="download_surveys"),
    path("retrieve/<int:survey_id>", load_survey_data, name="load_survey_data"),
    path("update/<int:survey_id>", update_survey, name="update_survey"),
    path("delete/<int:survey_id>", delete_survey, name="delete_survey"),
    path("respond_survey/<int:survey_id>", respond_survey, name="respond_survey"),
]

nom035/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('employees/retrieve/<int:employee_id>', load_employee_data, name='load_employee_data'),
    path('employees/register/', register_employee, name='register_employee'),
    path('employees/update/<int:employee_id>', update_employee, name='update_employee'),
    path('employees/delete/<int:employee_id>', delete_employee, name='delete_employee'),
    path('employees/', employees_view, name='employees_view'),
    path('employees/<int:employee_id>/<int:survey_id>', employee_answers_view, 
        name='employee_answers_view'),
    path('employees/<int:employee_id>', employee_details_view, 
        name='employee_details_view'),
    path('policy/', policy_view, name='policy_view'),
    path('update_password/', update_password, name='update_password'),
]

nom035/users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Company(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    social_denomination = models.CharField(max_length=180)
    address = models.CharField(max_length=300)
    main_activity = models.CharField(max_length=200)
    employees_code = models.CharField(max_length=4)

    def __str__(self):
        return self.social_denomination


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(
        "Company", on_delete=models.CASCADE, related_name="employees"
    )
    sex = models.BooleanField(null=True)
    birthdate = models.DateField(default=timezone.now)
    policy = models.BooleanField(default=False)

    @property
    def age(self):
        import datetime

        return int((datetime.date.today() - self.birthdate).days / 365.25)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


class InformationLog(models.Model):
    employee = models.ForeignKey(
        "Employee", on_delete=models.CASCADE, related_name="information_logs"
    )
    civil_status = models.IntegerField(null=True)
    educational_level = models.IntegerField(null=True)
    position = models.CharField(max_length=100, null=True)
    area = models.CharField(max_length=70, null=True)
    position_type = models.IntegerField(null=True)
    contract_type = models.IntegerField(null=True)
    personnel_type = models.IntegerField(null=True)
    working_day_type = models.IntegerField(null=True)
    shift_rotation = models.BooleanField(null=True)
    current_position_time = models.IntegerField(null=True)
    work_experience_time = models.IntegerField(null=True)

nom035/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import *
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from surveys.models import AnswerSheet, Survey

from . import choices
from .models import Employee, InformationLog


def login_view(request):
    if request.user.is_authenticated:
        return redirect("index_view")
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("index_view")
        else:
            messages.error(request, "El usuario o la contraseña son inconrrectos.")
            return redirect("login_view")
    else:
        return render(request, "login.html")


# Posible mejora
def user_logout(request):
    logout(request)
    return redirect("login_view")


def index_view(request):
    if request.user.is_authenticated:
        employee = is_employee(request.user)
        company = is_company(request.user)
        surveys = []
        graph_data = None
        rca = None  # Require clinical attention
        if company is not None:
            company = request.user.company
            surveys = company.surveys.order_by("-id")[:2]
            if surveys:
                rca, graph_data = company_index_data(surveys)
        else:
            employee = request.user.employee
            sheets = employee.answer_sheets.filter(final_answer="unanswered").order_by(
                "-id"
            )
            for sheet in sheets:
                surveys.append(sheet.survey)
        context = {
            "employee": employee,
            "company": company,
            "surveys": surveys,
            "graph_data": graph_data,
            "require_clinical_attention": rca,
        }
        return render(request, "users/index.html", context)
    else:
        return redirect("login_view")


def register_employee(request):
    if request.method == "POST":
        username = request.POST["username"]
        pwd = request.POST["password"]
        pwd_conf = request.POST["password_confirmation"]
        f_name = request.POST["first_name"]
        l_name = request.POST["last_name"]
        email = request.POST["email"]
        sex = request.POST["sex"]
        b_date = request.POST["birthdate"]
        civ_st = request.POST["civil_status"]
        educ_lvl = request.POST["educational_level"]
        pos = request.POST["position"]
        area = request.POST["area"]
        pos_type = request.POST["position_type"]
        contr_type = request.POST["contract_type"]
        pers_type = request.POST["personnel_type"]
        work_d_type = request.POST["working_day_type"]
        shft_rot = request.POST["shift_rotation"]
        curr_pos_t = request.POST["current_position_time"]
        work_exp_t = request.POST["work_experience_time"]

        company = is_company(request.user)
        if company is not None:
            employee_code = company.employees_code
            username = employee_code + username
        else:
            return redirect(_404(request, "Page not found", "404.html"))
        if User.objects.filter(username=username).exists():
            messages.error(request, "El nombre de usuario ya existe, prueba con otro")
            return redirect("user:employees_view")
        if User.objects.filter(email=email).exists():
            messages.error(request, "El email ingresado ya existe, prueba con otro")
            return redirect("user:employees_view")
        if pwd != pwd_conf and pwd != "":
            messages.error(request, "Las contraseñas no coinciden")
            return redirect("user:employees_view")
        new_user = User.objects.create_user(
            username=username,
            email=email,
            password=pwd,
            first_name=f_name,
            last_name=l_name,
        )
        employee = Employee.objects.create(
            user=new_user, sex=sex, birthdate=b_date, company=company
        )
        InformationLog.objects.create(
            employee=employee,
            civil_status=civ_st,
            educational_level=educ_lvl,
            position=pos,
            area=area,
            position_type=pos_type,
            contract_type=contr_type,
            personnel_type=pers_type,
            working_day_type=work_d_type,
            shift_rotation=shft_rot,
            current_position_time=curr_pos_t,
            work_experience_time=work_exp_t,
        )
    return redirect("user:employees_view")


def update_employee(request, employee_id):
    if request.method == "POST":
        f_name = request.POST["first_name"]
        l_name = request.POST["last_name"]
        email = request.POST["email"]
        pwd = request.POST["password"]
        pwd_conf = request.POST["password_confirmation"]
        b_date = request.POST["birthdate"]
        civ_st = request.POST["civil_status"]
        educ_lvl = request.POST["educational_level"]
        pos = request.POST["position"]
        area = request.POST["area"]
        pos_type = request.POST["position_type"]
        contr_type = request.POST["contract_type"]
        pers_type = request.POST["personnel_type"]
        work_d_type = request.POST["working_day_type"]
        shft_rot = request.POST["shift_rotation"]
        curr_pos_t = request.POST["current_position_time"]
        work_exp_t = request.POST["work_experience_time"]

        company = is_company(request.user)
        if company is not None:
            employee = get_object_or_404(Employee, id=employee_id)
            if employee.company == company:
                info = employee.information_logs.last()
            else:
                return redirect(_404(request, "Page not found", "404.html"))
        else:
            return redirect(_404(request, "Page not found", "404.html"))
        if pwd != "":
            if pwd != pwd_conf:
                messages.error(request, "Las contraseñas no coinciden")
            else:
                valid_pwd = password_validation(pwd)
                if valid_pwd == 0:
                    employee.user.set_password(pwd)
                else:
                    messages.error(request, valid_pwd)
        if User.objects.filter(email=email).exists() and employee.user.email != email:
            messages.error(request, "El email ingresado ya existe, prueba con otro")
        else:
            employee.user.email = email
        employee.birthdate = b_date
        employee.user.first_name = f_name
        employee.user.last_name = l_name
        employee.save()
        employee.user.save()
        InformationLog.objects.get_or_create(
            employee=employee,
            civil_status=civ_st,
            educational_level=educ_lvl,
            position=pos,
            area=area,
            position_type=pos_type,
            contract_type=contr_type,
            personnel_type=pers_type,
            working_day_type=work_d_type,
            shift_rotation=shft_rot,
            current_position_time=curr_pos_t,
            work_experience_time=work_exp_t,
        )
    return redirect("user:employees_view")


def load_employee_data(request, employee_id):
    if request.user.is_authenticated:
        company = is_company(request.user)
        if company is None:
            return redirect(_404(request, "Page not found", "404.html"))
        employee = get_object_or_404(Employee, id=employee_id)
        information_log = employee.information_logs.last()
        if employee.company == company:
            employee = [
                {
                    "first_name": employee.user.first_name,
                    "last_name": employee.user.last_name,
                    "email": employee.user.email,
                    "birthdate": employee.birthdate,
                    "civil_status": information_log.civil_status,
                    "educational_level": information_log.educational_level,
                    "position": information_log.position,
                    "area": information_log.area,
                    "position_type": information_log.position_type,
                    "contract_type": information_log.contract_type,
                    "personnel_type": information_log.personnel_type,
                    "working_day_type": information_log.working_day_type,
                    "shift_rotation": information_log.shift_rotation,
                    "current_position_time": information_log.current_position_time,
                    "work_experience_time": information_log.work_experience_time,
                }
            ]
            return JsonResponse(employee, content_type="application/json", safe=False)
    return redirect("index_view")


def password_validation(password):
    validators = [
        MinimumLengthValidator,
        CommonPasswordValidator,
        NumericPasswordValidator,
    ]
    try:
        for validator in validators:
            validator().validate(password)
        return 0
    except ValidationError as e:
        if (
            str(e)
            == "['This password is too short. It must contain at least 8 characters.']"
        ):
            return "La contraseña es demasiado corta. Debe contener por lo menos 8 caracteres"
        elif str(e) == "['This password is too common.']":
            return "La contraseña es muy común."
        elif str(e) == "['This password is entirely numeric.']":
            return "La contraseña no puede ser enteramente numérica. Añade letras y símbolos."
        else:
            return str(e)


def delete_employee(request, employee_id):
    company = is_company(request.user)
    if request.user.is_authenticated and company is not None:
        employee = get_object_or_404(Employee, id=employee_id)

nom035/templates/users/employee/_delete_modal.html
<div class="modal fade" id="deleteEmployeeModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Eliminar Empleado</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <p>
            ¿Está segur@ que desea eliminar a <strong id="deleteModalName"></strong> de su lista de empleados?
          </p>
          <p>
            Al hacerlo se borrará toda su información y las respuestas registradas de sus encuestas,
            esto no alterará ni pondrá en riesgo las encuestas de otros empleados.
          </p>
        </div>
        <form id="deleteEmployee" action="{% url 'user:delete_employee' 0 %}" method="POST"
          onsubmit="deleteEmployeeButton.disabled = true; return true;">
          {% csrf_token %}
          <div class="form-group" hidden>
            <label for="recipient-name" class="col-form-label">Id:</label>
            <input type="text" class="form-control" name="employee_id" value="{{employee.user.id}}">
          </div>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-danger" name="deleteEmployeeButton">Eliminar</button>
        </form>
      </div>
    </div>
  </div>
</div>

nom035/templates/users/employee/_register_modal.html
<div class="modal fade" id="registerEmployeeModal" tabindex="-1">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Registrar Empleado</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="registerEmployee" action="{% url 'user:register_employee' %}" method="POST" class="employeeForm"
          onsubmit="registerEmployeeButton.disabled = true; return true;">
          {% csrf_token %}
          <div class="form-row">
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="first_name">Nombre</label>
              <input id="first_name" type="text" class="form-control" placeholder="Nombre" name="first_name" required>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="last_name">Apellidos</label>
              <input id="last_name" type="text" class="form-control" placeholder="Apellidos" name="last_name" required>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="email">Email</label>
              <input id="email" type="email" class="form-control" placeholder="Email" name="email" required>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="username">Usuario</label>
              <input id="username" class="form-control" placeholder="Usuario" name="username" required>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="password">Contraseña</label>
              <input id="password" type="password" class="form-control" placeholder="Contraseña" name="password"
                required>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="password_confirmation">Confirmar contraseña</label>
              <input id="password_confirmation" type="password" class="form-control" placeholder="Contraseña"
                name="password_confirmation" required>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label>Sexo</label>
              <div class="d-flex justify-content-start">
                <div class="form-check m-1">
                  <input class="form-check-input" type="radio" name="sex" id="sex1" value="1" required>
                  <label class="form-check-label" for="sex1">
                    Masculino
                  </label>
                </div>
                <div class="form-check m-1">
                  <input class="form-check-input" type="radio" name="sex" id="sex2" value="0" required>
                  <label class="form-check-label" for="sex2">
                    Femenino
                  </label>
                </div>
              </div>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="birthday">Fecha de nacimiento</label>
              <input id="birthdate" type="date" class="form-control" placeholder="Fecha de nacimiento" name="birthdate"
                required>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="civil_status">Estado civil</label>
              <select id="civil_status" class="form-control" name="civil_status" required>
                <option value="">Selecciona una opción</option>
                {% for value, text in civil_status.items %}
                <option value="{{value}}">{{text}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="educational_level">Nivel de estudios</label>
              <select id="educational_level" class="form-control" name="educational_level" required>
                <option value="">Selecciona una opción</option>
                {% for value, text in educational_level.items %}
                <option value="{{value}}">{{text}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="position">Ocupacion/Profesión/Puesto</label>
              <input type="text" class="form-control" placeholder="Ocupacion/Profesión/Puesto" name="position"
                id="position" required>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="area">Departamento/Seccion/Área</label>
              <input type="text" class="form-control" placeholder="Departamento/Seccion/Área" name="area" id="area"
                required>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="position_type">Tipo de puesto</label>
              <select id="position_type" class="form-control" name=position_type required>
                <option value="">Selecciona una opción</option>
                {% for value, text in position_type.items %}
                <option value="{{value}}">{{text}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="contract_type">Tipo de contratación</label>
              <select id="contract_type" class="form-control" name=contract_type required>
                <option value="">Selecciona una opción</option>
                {% for value, text in contract_type.items %}
                <option value="{{value}}">{{text}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="personnel_type">Tipo de personal</label>
              <select id="personnel_type" class="form-control" name=personnel_type required>
                <option value="">Selecciona una opción</option>
                {% for value, text in personnel_type.items %}
                <option value="{{value}}">{{text}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="working_day_type">Tipo de jornada de trabajo</label>
              <select id="working_day_type" class="form-control" name=working_day_type required>
                <option value="">Selecciona una opción</option>
                {% for value, text in working_day_type.items %}
                <option value="{{value}}">{{text}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-12 form-group">
              <label>Realiza rotación de turnos</label>
              <div class="d-flex justify-content-start">
                <div class="form-check m-1">
                  <input class="form-check-input" type="radio" name="shift_rotation" id="shift_rotation1" value="1"
                    required>
                  <label class="form-check-label" for="shift_rotation">
                    Si
                  </label>
                </div>
                <div class="form-check m-1">
                  <input class="form-check-input" type="radio" name="shift_rotation" id="shift_rotation2" value="0"
                    required>
                  <label class="form-check-label" for="shift_rotation2">
                    No
                  </label>
                </div>
              </div>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="current_position_time">Tiempo en el puesto actual</label>
              <select id="current_position_time" class="form-control" name=current_position_time required>
                <option value="">Selecciona una opción</option>
                {% for value, text in current_position_time.items %}
                <option value="{{value}}">{{text}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-12 col-sm-6 col-xl-6 col-lg-6 col-md-6 form-group">
              <label for="work_experience_time">Tiempo experiencia laboral</label>
              <select id="work_experience_time" class="form-control" name=work_experience_time required>
                <option value="">Selecciona una opción</option>
                {% for value, text in work_experience_time.items %}
                <option value="{{value}}">{{text}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <button id="register-submit-btn" type="submit" class="btn btn-primary"
            name="registerEmployeeButton">Registrar</button>
        </form>
      </div>
    </div>
  </div>
</div>

nom035/templates/users/employee/employee_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row mt-3">
  <div class="col-12 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-6 offset-xl-3">
    {% include '_alerts.html' %}
  </div>
</div>
<div class="container-fluid">
  <div class="text-center">
    <h2>{{employee.user.first_name}} {{employee.user.last_name}}</h2>
    <h5 class="text-monospace">({{employee.user.username}})</h5>
    <button type="button" class="btn btn-outline-primary rounded-pill ed-emp" data-toggle="modal"
      data-target="#updateEmployeeModal" data-employee-id="{{employee.id}}">Editar
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor"
        xmlns="http://www.w3.org/2000/svg">
        <path
          d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
        <path fill-rule="evenodd"
          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
      </svg>
    </button>
    <button type="button" class="btn btn-outline-danger ml-3 rounded-pill del-emp" data-toggle="modal"
      data-target="#deleteEmployeeModal" data-employee-id="{{employee.id}}"
      data-employee-name="{{employee.user.first_name}} {{employee.user.last_name}}">Eliminar
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
        xmlns="http://www.w3.org/2000/svg">
        <path
          d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
        <path fill-rule="evenodd"
          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
      </svg>
    </button>

    <!-- Employee Information -->
    {% include './_employee_information.html' %}

    <!-- Survey table -->
    <div class="shadow-lg rounded mt-5 mb-3">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Encuesta</th>
            <th scope="col">
              <div class="text-center">
                Resultados
              </div>
            </th>
          </tr>
        </thead>
        <tbody>
          {% for sheet in sheets %}
          {% if sheet.final_answer == -1 %}
          <tr class="">
            <th scope="row">
              <a class="btn btn-block text-left" href=""> Guía {{ employee.survey.guide_number }} -
                {{sheet.survey.title}}</a>
            </th>
            <td>
              <div class="text-center">
                <span class="badge badge-primary badge-pill">Encuesta sin resolver</span>
              </div>
            </td>
          </tr>
          {% else %}
          <tr>
            <td>
              <a class="btn btn-block text-left"
                href="{% url 'user:employee_answers_view' employee.id sheet.survey.id%}">Guía
                {{ sheet.survey.guide_number }} - {{sheet.survey.title}}</a>
            </td>
            <td>
              {% if sheet.final_answer == "Muy alto" or sheet.final_answer == "Requiere atención clínica" %}
              <span class="badge text-white badge-pill" style="background-color:#E84258;">{{sheet.final_answer}}</span>
              {% elif sheet.final_answer == "Alto" %}
              <span class="badge text-white badge-pill" style="background-color:#FD8060;">{{sheet.final_answer}}</span>
              {% elif sheet.final_answer == "Medio" %}
              <span class="badge text-dark badge-pill" style="background-color:#FEE191;">{{sheet.final_answer}}</span>
              {% elif sheet.final_answer == "Bajo" %}
              <span class="badge text-white badge-pill" style="background-color:#B0D8A4;">{{sheet.final_answer}}</span>
              {% else %}
              <span class="badge text-white badge-pill" style="background-color:#58A1D9;">{{sheet.final_answer}}</span>
              {% endif %}
            </td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>


{% include './_update_modal.html' %}
{% include './_delete_modal.html' %}

{% endblock %}