nom035/nom035/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from users.views import login_view, index_view, user_logout, _404, _500

urlpatterns = [
    path('surveys/', include('surveys.urls', namespace="survey")),
    path('user/', include('users.urls', namespace="user")),
    path('management/', admin.site.urls),
    path('login/', login_view, name='login_view'),
    path('logout/', user_logout, name='user_logout'),
    path('', index_view, name='index_view'),
]

handler404 = _404
handler500 = _500

nom035/surveys/urls.py
from django.urls import path

from .views import *

app_name = "surveys"

urlpatterns = [
    path("", surveys_view, name="surveys_view"),
    path("<int:survey_id>", survey_details_view, name="survey_details_view"),
    path("report/<int:survey_id>", survey_report_view, name="survey_report_view"),
    path("assign_surveys", assign_surveys, name="assign_surveys"),
    path("create_survey", create_survey, name="create_survey"),
    path("download_surveys/<int:survey_id>", download_surveys, name="download_surveys"),
    path("retrieve/<int:survey_id>", load_survey_data, name="load_survey_data"),
    path("update/<int:survey_id>", update_survey, name="update_survey"),
    path("delete/<int:survey_id>", delete_survey, name="delete_survey"),
    path("respond_survey/<int:survey_id>", respond_survey, name="respond_survey"),
]

nom035/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('employees/retrieve/<int:employee_id>', load_employee_data, name='load_employee_data'),
    path('employees/register/', register_employee, name='register_employee'),
    path('employees/update/<int:employee_id>', update_employee, name='update_employee'),
    path('employees/delete/<int:employee_id>', delete_employee, name='delete_employee'),
    path('employees/', employees_view, name='employees_view'),
    path('employees/<int:employee_id>/<int:survey_id>', employee_answers_view, 
        name='employee_answers_view'),
    path('employees/<int:employee_id>', employee_details_view, 
        name='employee_details_view'),
    path('policy/', policy_view, name='policy_view'),
    path('update_password/', update_password, name='update_password'),
]

nom035/surveys/models.py
from django.db import models
from users.models import Employee, Company, InformationLog


class Survey(models.Model):
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name="surveys")
    title = models.CharField(max_length=150)
    responsible = models.CharField(max_length=70)
    responsible_id = models.IntegerField()
    conclusions = models.TextField(default='')
    method = models.CharField(max_length=30, default='')
    objective = models.TextField(default='')
    recommendations = models.TextField(default='')
    main_activities = models.CharField(max_length=200)
    guide_number = models.IntegerField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} - {self.date}"


class Section(models.Model):
    survey = models.ForeignKey(
        'Survey', on_delete=models.CASCADE, related_name='sections')
    content = models.CharField(max_length=200, default='')
    section_type = models.IntegerField()

    def __str__(self):
        return f"{self.survey.guide_number} - {self.content}"


class Question(models.Model):
    section = models.ForeignKey(
        'Section', on_delete=models.CASCADE, related_name='questions')
    number = models.IntegerField()
    content = models.CharField(max_length=200, default='')
    inverted = models.BooleanField()

    def __str__(self):
        return f"{self.section.survey.guide_number} - {self.number} - {self.content}"


class AnswerSheet(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='answer_sheets', default=1)
    survey = models.ForeignKey(
        'Survey', on_delete=models.CASCADE, related_name='answer_sheets')
    information_log = models.ForeignKey(
        InformationLog, on_delete=models.CASCADE, related_name='answer_sheets')
    date = models.DateField(auto_now_add=True)
    final_answer = models.CharField(max_length=30, default='unanswered')

    def __str__(self):
        return f"{self.employee} - {self.survey}"


class Answer(models.Model):
    question = models.ForeignKey(
        'Question', on_delete=models.CASCADE, related_name='answers')
    answer_sheet = models.ForeignKey(
        'AnswerSheet', on_delete=models.CASCADE, related_name='answers')
    value = models.IntegerField()
    content = models.CharField(max_length=15)
    def __str__(self):
        return f"{self.question} - {self.value}"


class Grade(models.Model):
    answer_sheet = models.OneToOneField(
        'AnswerSheet', on_delete=models.CASCADE, related_name='grade')
    work_environment = models.CharField(max_length=10)
    activity_factor = models.CharField(max_length=10)
    time_organization = models.CharField(max_length=10)
    leadership_relationship = models.CharField(max_length=10)
    organizational_environment = models.CharField(max_length=10, blank=True)
    work_environment_conditions = models.CharField(max_length=10)
    working_load = models.CharField(max_length=10)
    work_lack_control = models.CharField(max_length=10)
    working_day = models.CharField(max_length=10)
    family_work_relationship = models.CharField(max_length=10)
    leadership = models.CharField(max_length=10)
    work_relationship = models.CharField(max_length=10)
    violence = models.CharField(max_length=10)
    performance_recognition = models.CharField(max_length=10, blank=True)
    sense_belonging_instability = models.CharField(max_length=10, blank=True)

nom035/surveys/views.py
import json
import mimetypes
import os
from wsgiref.util import FileWrapper

import pandas as pd
from django.contrib import messages

# from django.core.files.temp import NamedTemporaryFile
from django.http import JsonResponse, StreamingHttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from users.views import _404, is_company, is_employee

from .models import Answer, AnswerSheet, Grade, Question, Section, Survey


def surveys_view(request):
    company = is_company(request.user)
    if request.user.is_authenticated and company is not None:
        surveys = company.surveys.order_by("-id")
        context = {
            "surveys": surveys,
        }
        return render(request, "surveys/survey_list.html", context)
    return redirect(_404(request, "Page not found", "404.html"))


def survey_report_view(request, survey_id):
    try:
        company = is_company(request.user)
        if request.user.is_authenticated and company is not None:
            survey = get_object_or_404(company.surveys, id=survey_id)
            sheets = AnswerSheet.objects.filter(survey=survey).exclude(
                final_answer="unanswered"
            )
            answered_count = sheets.count()
            value_map = {"Nulo": 0, "Bajo": 1, "Medio": 2, "Alto": 3, "Muy alto": 4}
            titles_mapping = {
                "work_environment": "Ambiente de trabajo",
                "activity_factor": "Factores propios de la actividad",
                "time_organization": "Organización del tiempo de trabajo",
                "leadership_relationship": "Liderazgo y relaciones en el trabajo",
                "organizational_environment": "Entorno organizacional",
                "work_environment_conditions": "Condiciones en el ambiente de trabajo",
                "working_load": "Carga de trabajo",
                "work_lack_control": "Falta de control sobre el trabajo",
                "working_day": "Jornada de trabajo",
                "family_work_relationship": "Interferencia en la relación trabajo y familia",
                "leadership": "Liderazgo",
                "work_relationship": "Relaciones en el trabajo",
                "violence": "Violencia",
                "performance_recognition": "Reconocimiento del desempeño",
                "sense_belonging_instability": "Insuficiente sentido de pertenencia e inestabilidad",
            }

            def init_report_structure(guide_number):
                report_structure = {
                    "category": {
                        "work_environment": [0] * 5,
                        "activity_factor": [0] * 5,
                        "time_organization": [0] * 5,
                        "leadership_relationship": [0] * 5,
                    },
                    "domain": {
                        "work_environment_conditions": [0] * 5,
                        "working_load": [0] * 5,
                        "work_lack_control": [0] * 5,
                        "working_day": [0] * 5,
                        "family_work_relationship": [0] * 5,
                        "leadership": [0] * 5,
                        "work_relationship": [0] * 5,
                        "violence": [0] * 5,
                    },
                }
                if guide_number == 3:
                    report_structure["category"]["organizational_environment"] = [0] * 5
                    report_structure["domain"].update(
                        {
                            "performance_recognition": [0] * 5,
                            "sense_belonging_instability": [0] * 5,
                        }
                    )
                return report_structure

            report = init_report_structure(survey.guide_number)
            for answer_sheet in sheets:
                grades = Grade.objects.filter(answer_sheet=answer_sheet.pk)
                for grade in grades:
                    for key in report:
                        for attribute in report[key]:
                            if hasattr(grade, attribute):
                                value = getattr(grade, attribute)
                                report[key][attribute][value_map[value]] += 1

            # Calculate percentages
            for category in report:
                for key, values in report[category].items():
                    report[category][key] = [
                        round((value / answered_count) * 100, 2) for value in values
                    ]

            report_for_template = []
            for category, values in report["category"].items():
                report_for_template.append(
                    {
                        "type": "category",
                        "name": titles_mapping[category],
                        "data": values,
                        "id": f"report_II_III_chart_{category}",
                    }
                )

            for domain, values in report["domain"].items():
                report_for_template.append(
                    {
                        "type": "domain",
                        "name": titles_mapping[domain],
                        "data": values,
                        "id": f"report_II_III_chart_{domain}",
                    }
                )

            context = {
                "survey": survey,
                "report": report_for_template,
            }
            return render(request, "surveys/survey_report.html", context)
    except Survey.DoesNotExist:
        return redirect(_404(request, "Page not found", "404.html"))


def survey_details_view(request, survey_id):
    company = is_company(request.user)
    try:
        if request.user.is_authenticated and company is not None:
            survey = company.surveys.get(id=survey_id)
            sheets = AnswerSheet.objects.filter(survey=survey)
            answered = sheets.exclude(final_answer="unanswered")
            unanswered = sheets.filter(final_answer="unanswered")
            context = {
                "survey": survey,
                "answered": answered,
                "unanswered": unanswered,
            }
            return render(request, "surveys/survey_details.html", context)
    except Survey.DoesNotExist:
        return redirect(_404(request, "Page not found", "404.html"))


def create_survey(request):
    user = request.user
    company = is_company(user)
    if request.user.is_authenticated and company is not None:
        if request.method == "POST":
            responsible = request.POST["responsible"]
            main_activities = request.POST["main_activities"]
            responsible_id = request.POST["responsible_id"]
            if responsible_id == "":
                responsible_id = 0
            employees = company.employees.all()
            company_size = employees.count()
            filenames = []
            if company_size > 50:
                filenames.append("./nom035/static/surveys/guide_III.txt")
            elif company_size > 15:
                filenames.append("./nom035/static/surveys/guide_II.txt")
            filenames.append("./nom035/static/surveys/guide_I.txt")
            for filename in filenames:
                survey = None
                section = None
                with open(filename, encoding="utf-8") as survey_guide:
                    for line in survey_guide.readlines()[1:]:
                        data = line.split("|")
                        if data[0].isdigit():
                            survey = Survey.objects.create(
                                company=company,
                                main_activities=main_activities,
                                guide_number=data[0],
                                responsible=responsible,
                                responsible_id=responsible_id,
                                title=data[2].strip(),
                            )
                        elif data[0] == "Section":
                            section = Section.objects.create(
                                survey=survey, content=data[2], section_type=data[1]
                            )
                        else:
                            Question.objects.create(
                                section=section,
                                number=data[1],
                                content=data[2],
                                inverted=data[3],
                            )
                    link_survey(survey, employees)
            return redirect("survey:surveys_view")
        else:
            return redirect("survey:surveys_view")
    else:
        return redirect(_404(request, "Page not found", "404.html"))


def link_survey(survey, employees):
    for employee in employees:
        info_log = employee.information_logs.last()
        AnswerSheet.objects.create(
            employee=employee, information_log=info_log, survey=survey
        )
    return 0


def assign_surveys(request):
    company = is_company(request.user)
    if request.user.is_authenticated and company is not None:
        if request.method == "POST":
            surveys = reversed(company.surveys.order_by("-id")[:2])
            for survey in surveys:
                employees = company.employees.all()
                for employee in employees:
                    if not employee.answer_sheets.filter(survey=survey).exists():
                        info_log = employee.information_logs.last()
                        AnswerSheet.objects.create(
                            survey=survey, employee=employee, information_log=info_log
                        )
            messages.success(
                request,
                "Los empleados faltantes se han asignado a las encuestas activas.",
            )
            return redirect("survey:surveys_view")
    return redirect(_404(request, "Page not found", "404.html"))


def update_survey(request, survey_id):
    company = is_company(request.user)

nom035/templates/surveys/_yes_no.html
<div id="{{switch}}" class="d-flex justify-content-start">
  <div class="p-2">
    <input id="yes-{{question.id}}" type="radio" name="{{question.id}}" value="1" {{required}}>
    <label class="form-check-label" for="yes-{{question.id}}">
      Si
    </label>
  </div>
  <div class="p-2">
    <input id="no-{{question.id}}" type="radio" name="{{question.id}}" value="0" {{required}}>
    <label class="form-check-label" for="no-{{question.id}}">
      No
    </label>
  </div>
</div>

nom035/templates/surveys/survey_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row mt-3">
  <div class="col-12 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-6 offset-xl-3">
    {% include '_alerts.html' %}
  </div>
</div>
<div class="container-fluid">
  <div class="text-center">
    <h2>{{survey.title}}</h2>
    <h5 class="text-monospace">({{survey.date|date:'d/m/Y'}})</h5>
    {% if survey.guide_number > 1 %}
    <button type="button" onclick="location.href='{% url 'survey:survey_report_view' survey_id=survey.id %}'"
      class="btn btn-outline-info ml-3 rounded-pill" data-survey-id="{{survey.id}}">Reporte
      <a href="{% url 'survey:surveys_view' as survey_url %}"><svg xmlns="http://www.w3.org/2000/svg" width="16"
          height="16" fill="currentColor" class="bi bi-bar-chart-line" viewBox="0 0 16 16">
          <path
            d="M11 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h1V7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7h1zm1 12h2V2h-2zm-3 0V7H7v7zm-5 0v-3H2v3z" />
        </svg>
      </a>
    </button>
    {% endif %}
    <button type="button" class="btn btn-outline-primary ml-3 rounded-pill ed-surv" data-toggle="modal"
      data-target="#updateSurveyModal" data-survey-id="{{survey.id}}">Editar
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor"
        xmlns="http://www.w3.org/2000/svg">
        <path
          d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
        <path fill-rule="evenodd"
          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
      </svg>
    </button>
    <button type="button" class="btn btn-outline-danger ml-3 rounded-pill del-surv" data-toggle="modal"
      data-target="#deleteSurveyModal" data-survey-id="{{survey.id}}" data-survey-title="{{survey.title}}">Eliminar
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
        xmlns="http://www.w3.org/2000/svg">
        <path
          d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
        <path fill-rule="evenodd"
          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
      </svg>
    </button>

    <!-- Survey Information -->
    {% include './_survey_information.html' %}

    <!-- Employees -->
    <div class="container mt-4 mb-4">
      <div class="row">
        <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
          <div class="card shadow-lg rounded">
            <div class="card-header bg-light text-body">Resueltas
            </div>
            <div class="card-body">
              {% if answered %}
              {% for sheet in answered %}
              <div class="row">
                <div class="col text-left">
                  <p class="card-text">{{sheet.employee.user.first_name}} {{sheet.employee.user.last_name}}
                    ({{sheet.employee.user.username}})</p>
                </div>
                <div class="col text-right">
                  <a href="{% url 'user:employee_answers_view' sheet.employee.id sheet.survey.id %}"
                    class="text-dark text-decoration-none">
                    Ver resultados <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye-fill"
                      fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                      <path fill-rule="evenodd"
                        d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                    </svg>
                  </a>
                </div>
              </div>
              {% endfor %}
              {% else %}
              <p class="card-text">Ningun empleado ha resuelto la encuesta.</p>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
          <div class="card shadow-lg rounded">
            <div class="card-header bg-light text-body">Sin resolver</div>
            <div class="card-body">
              {% if unanswered %}
              {% for sheet in unanswered %}
              <div class="row">
                <div class="col text-left">
                  <p class="card-text">{{sheet.employee.user.first_name}} {{sheet.employee.user.last_name}}
                    ({{sheet.employee.user.username}})</p>
                </div>
              </div>
              {% endfor %}
              {% else %}
              <p class="card-text">Todos los empleados han resuelto la encuesta.</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% include './_update_modal.html' %}
{% include './_delete_modal.html' %}

{% endblock %}

nom035/templates/surveys/survey_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-3">
  <div class="col-12 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-6 offset-xl-3">
    {% include '_alerts.html' %}
  </div>
</div>
<div class="container-fluid">
  <div class="text-center">
    <h2>Encuestas</h2>
  </div>
  <button type="button" class="btn btn-outline-success rounded-pill m-3" data-toggle="modal"
    data-target="#createSurveyModal">
    Crear Encuesta
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-plus-fill" fill="currentColor"
      xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd"
        d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM8.5 7a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V11a.5.5 0 0 0 1 0V9.5H10a.5.5 0 0 0 0-1H8.5V7z" />
    </svg>
  </button>
  {% if surveys %}
  <button type="button" class="btn btn-outline-info rounded-pill" data-toggle="modal" data-target="#assignSurveysModal">
    Asignar Encuesta(s)
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-people-fill" fill="currentColor"
      xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd"
        d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5.784 6A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
    </svg>
  </button>
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Encuesta</th>
        <th scope="col">
          <div class="text-center">
            Fecha
          </div>
        </th>
        <th scope="col">
          <div class="text-center">
            Acción
          </div>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for survey in surveys %}
      <tr>
        <td>
          <a class="btn btn-block text-left" href="{% url 'survey:survey_details_view' survey.id %}">
            {{ survey.title }}</a>
        </td>
        <td class="align-middle">
          <div class="text-center">
            {{survey.date|date:"d/m/Y"}}
          </div>
        </td>
        <td class="align-middle">
          <div class="text-center">
            {% if survey.guide_number > 1 %}
            <a type="button" class="btn btn-outline-info rounded-circle"
              href="{% url 'survey:survey_report_view' survey_id=survey.id %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-bar-chart-line" viewBox="0 0 16 16">
                <path
                  d="M11 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h1V7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7h1zm1 12h2V2h-2zm-3 0V7H7v7zm-5 0v-3H2v3z" />
              </svg>
            </a>
            {% else %}
            <a type="button" class="btn btn-outline-secondary rounded-circle disabled" aria-disabled="true"
              onclick="return false;">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-bar-chart-line" viewBox="0 0 16 16">
                <path
                  d="M11 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h1V7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7h1zm1 12h2V2h-2zm-3 0V7H7v7zm-5 0v-3H2v3z" />
              </svg>
            </a>
            {% endif %}
            <a type="button" class="btn btn-outline-success rounded-circle"
              href="{% url 'survey:download_surveys' survey.id %}" data-survey-id="{{survey.id}}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download"
                viewBox="0 0 16 16">
                <path
                  d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
                <path
                  d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
              </svg>
            </a>
            <button type="button" class="btn btn-outline-primary rounded-circle ed-surv" data-toggle="modal"
              data-target="#updateSurveyModal" data-survey-id="{{survey.id}}">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                <path fill-rule="evenodd"
                  d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
              </svg>
            </button>
            <button type="button" class="btn btn-outline-danger rounded-circle ml-2 del-surv" data-toggle="modal"
              data-target="#deleteSurveyModal" data-survey-id="{{survey.id}}" data-survey-title="{{survey.title}}">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                <path fill-rule="evenodd"
                  d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
              </svg>
            </button>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
</div>


{% include './_create_modal.html' %}
{% include './_update_modal.html' %}
{% include './_delete_modal.html' %}
{% include './_assign_surveys_modal.html' %}

{% endblock %}